import { PrismaService } from '../database/prisma.service';
import { CreatePilgrimDto, UpdatePilgrimDto, PilgrimQueryDto } from './dto/pilgrim.dto';
import * as ExcelJS from 'exceljs';
export declare class PilgrimsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createPilgrimDto: CreatePilgrimDto, tenantId: string): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }>;
    findAll(query: PilgrimQueryDto, tenantId: string, currentUser: any): Promise<{
        pilgrims: ({
            booking: {
                id: string;
                customer: {
                    name: string;
                    id: string;
                };
                booking_code: string;
            };
        } & {
            name: string;
            email: string | null;
            id: string;
            tenant_id: string;
            phone: string | null;
            status: string;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            address: string | null;
            id_type: string;
            id_number: string;
            birth_date: Date;
            gender: string;
            customer_id: string;
            booking_id: string;
            birth_place: string;
            passport_number: string | null;
            passport_expiry: Date | null;
            family_relationship: string;
            emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
            room_number: string | null;
            building: string | null;
            floor: number | null;
            documents: import("@prisma/client/runtime/library").JsonValue[];
            document_completion: number;
        })[];
        total: number;
        pagination: {
            page: number;
            limit: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    search(query: string, limit: number, tenantId: string): Promise<{
        name: string;
        id: string;
        phone: string;
        id_number: string;
        booking_id: string;
        passport_number: string;
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        booking: {
            id: string;
            package: {
                name: string;
                id: string;
                code: string;
            };
            customer: {
                name: string;
                id: string;
                phone: string;
            };
            booking_code: string;
        };
    } & {
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }>;
    update(id: string, updatePilgrimDto: UpdatePilgrimDto, tenantId: string, currentUser: any): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }>;
    remove(id: string, tenantId: string): Promise<void>;
    getStats(tenantId: string): Promise<{
        total: any;
        byGender: any;
        byNationality: any;
        byMaritalStatus: any;
        recentCount: any;
    }>;
    exportToExcel(query: PilgrimQueryDto, tenantId: string): Promise<ExcelJS.Buffer>;
    bulkCreate(pilgrimsData: CreatePilgrimDto[], tenantId: string): Promise<{
        created: number;
        failed: number;
        errors: string[];
    }>;
    assignToBooking(pilgrimId: string, bookingId: string, tenantId: string): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }>;
    removeFromBooking(pilgrimId: string, tenantId: string): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }>;
}
