import { PrismaService } from '../database/prisma.service';
import { CreatePaymentDto, UpdatePaymentDto, PaymentQueryDto, RefundPaymentDto, PaymentWebhookDto } from './dto/payment.dto';
export declare class PaymentsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createPaymentDto: CreatePaymentDto, tenantId: string): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    findAll(query: PaymentQueryDto, tenantId: string, currentUser: any): Promise<{
        payments: {
            method: import(".prisma/client").$Enums.PaymentMethod;
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.PaymentStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            amount: number;
            notes: string | null;
            created_by: string;
            booking_id: string | null;
            invoice_id: string;
            provider: import(".prisma/client").$Enums.PaymentProvider;
            provider_reference: string | null;
            paid_at: Date | null;
            provider_response: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        total: number;
        pagination: {
            page: number;
            limit: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    findOne(id: string, tenantId: string): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    update(id: string, updatePaymentDto: UpdatePaymentDto, tenantId: string, currentUser: any): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    refund(id: string, refundDto: RefundPaymentDto, tenantId: string): Promise<any>;
    getStats(tenantId: string): Promise<{
        total: number;
        completed: number;
        pending: number;
        failed: number;
        refunded: number;
        totalAmount: number;
        byMethod: {
            method: import(".prisma/client").$Enums.PaymentMethod;
            count: number;
            totalAmount: number;
        }[];
        byProvider: {
            provider: import(".prisma/client").$Enums.PaymentProvider;
            count: number;
            totalAmount: number;
        }[];
        recentCount: number;
    }>;
    processWebhook(provider: string, webhookData: PaymentWebhookDto, tenantId?: string): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    cancel(id: string, tenantId: string): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    retry(id: string, tenantId: string): Promise<{
        method: import(".prisma/client").$Enums.PaymentMethod;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PaymentStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        amount: number;
        notes: string | null;
        created_by: string;
        booking_id: string | null;
        invoice_id: string;
        provider: import(".prisma/client").$Enums.PaymentProvider;
        provider_reference: string | null;
        paid_at: Date | null;
        provider_response: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    private updateInvoicePaidAmount;
}
