import { PrismaService } from '../database/prisma.service';
import { CreatePackageDto, UpdatePackageDto, PackageQueryDto } from './dto/package.dto';
import { PackageStatus } from '@prisma/client';
import * as ExcelJS from 'exceljs';
export declare class PackagesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createPackageDto: CreatePackageDto, tenantId: string): Promise<{
        name: string;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PackageStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        code: string;
        description: string | null;
        type: import(".prisma/client").$Enums.PackageType;
        period_from: Date;
        period_to: Date;
        quota: number;
        hotels: import("@prisma/client/runtime/library").JsonValue[];
        flights: import("@prisma/client/runtime/library").JsonValue[];
        itinerary: import("@prisma/client/runtime/library").JsonValue[];
        price_quad: number;
        price_triple: number;
        price_double: number;
        price_single: number;
        inclusions: string[];
        exclusions: string[];
        terms: string | null;
        notes: string | null;
        featured_image_url: string | null;
        gallery_images: string[];
        documents_required: string[];
        quota_booked: number;
    }>;
    findAll(query: PackageQueryDto, tenantId: string, currentUser: any): Promise<{
        packages: {
            name: string;
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.PackageStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            code: string;
            description: string | null;
            type: import(".prisma/client").$Enums.PackageType;
            period_from: Date;
            period_to: Date;
            quota: number;
            hotels: import("@prisma/client/runtime/library").JsonValue[];
            flights: import("@prisma/client/runtime/library").JsonValue[];
            itinerary: import("@prisma/client/runtime/library").JsonValue[];
            price_quad: number;
            price_triple: number;
            price_double: number;
            price_single: number;
            inclusions: string[];
            exclusions: string[];
            terms: string | null;
            notes: string | null;
            featured_image_url: string | null;
            gallery_images: string[];
            documents_required: string[];
            quota_booked: number;
        }[];
        total: number;
        pagination: {
            page: number;
            limit: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    findPublished(tenantId: string): Promise<{
        name: string;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PackageStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        code: string;
        description: string | null;
        type: import(".prisma/client").$Enums.PackageType;
        period_from: Date;
        period_to: Date;
        quota: number;
        hotels: import("@prisma/client/runtime/library").JsonValue[];
        flights: import("@prisma/client/runtime/library").JsonValue[];
        itinerary: import("@prisma/client/runtime/library").JsonValue[];
        price_quad: number;
        price_triple: number;
        price_double: number;
        price_single: number;
        inclusions: string[];
        exclusions: string[];
        terms: string | null;
        notes: string | null;
        featured_image_url: string | null;
        gallery_images: string[];
        documents_required: string[];
        quota_booked: number;
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        name: string;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PackageStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        code: string;
        description: string | null;
        type: import(".prisma/client").$Enums.PackageType;
        period_from: Date;
        period_to: Date;
        quota: number;
        hotels: import("@prisma/client/runtime/library").JsonValue[];
        flights: import("@prisma/client/runtime/library").JsonValue[];
        itinerary: import("@prisma/client/runtime/library").JsonValue[];
        price_quad: number;
        price_triple: number;
        price_double: number;
        price_single: number;
        inclusions: string[];
        exclusions: string[];
        terms: string | null;
        notes: string | null;
        featured_image_url: string | null;
        gallery_images: string[];
        documents_required: string[];
        quota_booked: number;
    }>;
    update(id: string, updatePackageDto: UpdatePackageDto, tenantId: string): Promise<{
        name: string;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PackageStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        code: string;
        description: string | null;
        type: import(".prisma/client").$Enums.PackageType;
        period_from: Date;
        period_to: Date;
        quota: number;
        hotels: import("@prisma/client/runtime/library").JsonValue[];
        flights: import("@prisma/client/runtime/library").JsonValue[];
        itinerary: import("@prisma/client/runtime/library").JsonValue[];
        price_quad: number;
        price_triple: number;
        price_double: number;
        price_single: number;
        inclusions: string[];
        exclusions: string[];
        terms: string | null;
        notes: string | null;
        featured_image_url: string | null;
        gallery_images: string[];
        documents_required: string[];
        quota_booked: number;
    }>;
    remove(id: string, tenantId: string): Promise<void>;
    changeStatus(id: string, status: PackageStatus, tenantId: string): Promise<void>;
    checkAvailability(id: string, tenantId: string): Promise<{
        quota: number;
        booked: number;
        available: number;
        isFullyBooked: boolean;
        status: string;
        percentageBooked: number;
    }>;
    duplicate(id: string, tenantId: string): Promise<{
        name: string;
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.PackageStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        code: string;
        description: string | null;
        type: import(".prisma/client").$Enums.PackageType;
        period_from: Date;
        period_to: Date;
        quota: number;
        hotels: import("@prisma/client/runtime/library").JsonValue[];
        flights: import("@prisma/client/runtime/library").JsonValue[];
        itinerary: import("@prisma/client/runtime/library").JsonValue[];
        price_quad: number;
        price_triple: number;
        price_double: number;
        price_single: number;
        inclusions: string[];
        exclusions: string[];
        terms: string | null;
        notes: string | null;
        featured_image_url: string | null;
        gallery_images: string[];
        documents_required: string[];
        quota_booked: number;
    }>;
    getStats(tenantId: string): Promise<{
        total: number;
        published: number;
        draft: number;
        full: number;
        available: number;
        byType: {
            type: import(".prisma/client").$Enums.PackageType;
            count: number;
        }[];
        averagePrices: {
            quad: number;
            double: number;
        };
    }>;
    exportToExcel(query: PackageQueryDto, tenantId: string): Promise<ExcelJS.Buffer>;
}
