import { PrismaService } from '../database/prisma.service';
import { CreateInvoiceDto, UpdateInvoiceDto, InvoiceQueryDto } from './dto/invoice.dto';
export declare class InvoicesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createInvoiceDto: CreateInvoiceDto, tenantId: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        terms: string | null;
        notes: string | null;
        customer_id: string;
        tax_amount: number;
        discount_amount: number;
        remaining_amount: number;
        created_by: string;
        booking_id: string;
        invoice_number: string;
        issue_date: Date;
        due_date: Date;
        paid_date: Date | null;
        items: import("@prisma/client/runtime/library").JsonValue[];
        subtotal: number;
        total_amount: number;
        paid_amount: number;
    }>;
    findAll(query: InvoiceQueryDto, tenantId: string, currentUser: any): Promise<{
        invoices: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        }[];
        total: number;
        pagination: {
            page: number;
            limit: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    findOne(id: string, tenantId: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        terms: string | null;
        notes: string | null;
        customer_id: string;
        tax_amount: number;
        discount_amount: number;
        remaining_amount: number;
        created_by: string;
        booking_id: string;
        invoice_number: string;
        issue_date: Date;
        due_date: Date;
        paid_date: Date | null;
        items: import("@prisma/client/runtime/library").JsonValue[];
        subtotal: number;
        total_amount: number;
        paid_amount: number;
    }>;
    update(id: string, updateInvoiceDto: UpdateInvoiceDto, tenantId: string, currentUser: any): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        terms: string | null;
        notes: string | null;
        customer_id: string;
        tax_amount: number;
        discount_amount: number;
        remaining_amount: number;
        created_by: string;
        booking_id: string;
        invoice_number: string;
        issue_date: Date;
        due_date: Date;
        paid_date: Date | null;
        items: import("@prisma/client/runtime/library").JsonValue[];
        subtotal: number;
        total_amount: number;
        paid_amount: number;
    }>;
    cancel(id: string, tenantId: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        terms: string | null;
        notes: string | null;
        customer_id: string;
        tax_amount: number;
        discount_amount: number;
        remaining_amount: number;
        created_by: string;
        booking_id: string;
        invoice_number: string;
        issue_date: Date;
        due_date: Date;
        paid_date: Date | null;
        items: import("@prisma/client/runtime/library").JsonValue[];
        subtotal: number;
        total_amount: number;
        paid_amount: number;
    }>;
    sendInvoice(id: string, tenantId: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        terms: string | null;
        notes: string | null;
        customer_id: string;
        tax_amount: number;
        discount_amount: number;
        remaining_amount: number;
        created_by: string;
        booking_id: string;
        invoice_number: string;
        issue_date: Date;
        due_date: Date;
        paid_date: Date | null;
        items: import("@prisma/client/runtime/library").JsonValue[];
        subtotal: number;
        total_amount: number;
        paid_amount: number;
    }>;
    getStats(tenantId: string): Promise<{
        total: number;
        draft: number;
        sent: number;
        paid: number;
        overdue: number;
        cancelled: number;
        totalAmount: number;
        paidAmount: number;
        outstandingAmount: number;
        recentCount: number;
    }>;
}
