import { InvoicesService } from './invoices.service';
import { CreateInvoiceDto, UpdateInvoiceDto, InvoiceQueryDto } from './dto/invoice.dto';
export declare class InvoicesController {
    private readonly invoicesService;
    constructor(invoicesService: InvoicesService);
    create(createInvoiceDto: CreateInvoiceDto, req: any): Promise<{
        success: boolean;
        data: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        };
        message: string;
    }>;
    findAll(query: InvoiceQueryDto, req: any): Promise<{
        success: boolean;
        data: {
            invoices: {
                id: string;
                tenant_id: string;
                status: import(".prisma/client").$Enums.InvoiceStatus;
                created_at: Date;
                updated_at: Date;
                deleted_at: Date | null;
                terms: string | null;
                notes: string | null;
                customer_id: string;
                tax_amount: number;
                discount_amount: number;
                remaining_amount: number;
                created_by: string;
                booking_id: string;
                invoice_number: string;
                issue_date: Date;
                due_date: Date;
                paid_date: Date | null;
                items: import("@prisma/client/runtime/library").JsonValue[];
                subtotal: number;
                total_amount: number;
                paid_amount: number;
            }[];
            total: number;
            pagination: {
                page: number;
                limit: number;
                totalPages: number;
                hasNext: boolean;
                hasPrev: boolean;
            };
        };
        message: string;
    }>;
    getStats(req: any): Promise<{
        success: boolean;
        data: {
            total: number;
            draft: number;
            sent: number;
            paid: number;
            overdue: number;
            cancelled: number;
            totalAmount: number;
            paidAmount: number;
            outstandingAmount: number;
            recentCount: number;
        };
        message: string;
    }>;
    findOne(id: string, req: any): Promise<{
        success: boolean;
        data: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        };
        message: string;
    }>;
    update(id: string, updateInvoiceDto: UpdateInvoiceDto, req: any): Promise<{
        success: boolean;
        data: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        };
        message: string;
    }>;
    sendInvoice(id: string, req: any): Promise<{
        success: boolean;
        data: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        };
        message: string;
    }>;
    cancel(id: string, req: any): Promise<{
        success: boolean;
        data: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        };
        message: string;
    }>;
}
