import { PrismaService } from '../database/prisma.service';
import { CreateBookingDto, UpdateBookingDto, BookingQueryDto } from './dto/booking.dto';
import { BookingStatus } from '@prisma/client';
import * as ExcelJS from 'exceljs';
export declare class BookingsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createBookingDto: CreateBookingDto, tenantId: string, currentUser: any): Promise<{
        package: {
            name: string;
            id: string;
            code: string;
        };
        customer: {
            name: string;
            email: string;
            id: string;
            phone: string;
        };
    } & {
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    }>;
    findAll(query: BookingQueryDto, tenantId: string, currentUser: any): Promise<{
        bookings: ({
            _count: {
                pilgrims: number;
            };
            package: {
                name: string;
                id: string;
                code: string;
                period_from: Date;
                period_to: Date;
            };
            customer: {
                name: string;
                email: string;
                id: string;
                phone: string;
            };
        } & {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.BookingStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            room_type: import(".prisma/client").$Enums.RoomType;
            notes: string | null;
            customer_id: string;
            package_id: string;
            booking_code: string;
            payment_status: import(".prisma/client").$Enums.PaymentStatus;
            number_of_pilgrims: number;
            special_requests: string | null;
            base_price: number;
            tax_amount: number;
            additional_fees: number;
            discount_amount: number;
            total_price: number;
            dp_amount: number;
            dp_paid: number;
            remaining_amount: number;
            remaining_paid: number;
            total_paid: number;
            booking_date: Date;
            confirmation_date: Date | null;
            payment_complete_date: Date | null;
            departure_date: Date;
            return_date: Date;
            created_by: string;
            updated_by: string | null;
        })[];
        total: number;
        pagination: {
            page: number;
            limit: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    search(query: string, limit: number, tenantId: string): Promise<({
        package: {
            name: string;
            id: string;
            code: string;
        };
        customer: {
            name: string;
            id: string;
        };
    } & {
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    })[]>;
    findOne(id: string, tenantId: string): Promise<{
        pilgrims: {
            name: string;
            email: string | null;
            id: string;
            tenant_id: string;
            phone: string | null;
            status: string;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            address: string | null;
            id_type: string;
            id_number: string;
            birth_date: Date;
            gender: string;
            customer_id: string;
            booking_id: string;
            birth_place: string;
            passport_number: string | null;
            passport_expiry: Date | null;
            family_relationship: string;
            emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
            room_number: string | null;
            building: string | null;
            floor: number | null;
            documents: import("@prisma/client/runtime/library").JsonValue[];
            document_completion: number;
        }[];
        invoices: {
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            terms: string | null;
            notes: string | null;
            customer_id: string;
            tax_amount: number;
            discount_amount: number;
            remaining_amount: number;
            created_by: string;
            booking_id: string;
            invoice_number: string;
            issue_date: Date;
            due_date: Date;
            paid_date: Date | null;
            items: import("@prisma/client/runtime/library").JsonValue[];
            subtotal: number;
            total_amount: number;
            paid_amount: number;
        }[];
        payments: {
            method: import(".prisma/client").$Enums.PaymentMethod;
            id: string;
            tenant_id: string;
            status: import(".prisma/client").$Enums.PaymentStatus;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            amount: number;
            notes: string | null;
            created_by: string;
            booking_id: string | null;
            invoice_id: string;
            provider: import(".prisma/client").$Enums.PaymentProvider;
            provider_reference: string | null;
            paid_at: Date | null;
            provider_response: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        package: {
            name: string;
            id: string;
            code: string;
        };
        customer: {
            name: string;
            email: string;
            id: string;
            phone: string;
        };
        creator: {
            name: string;
            id: string;
        };
        updater: {
            name: string;
            id: string;
        };
    } & {
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    }>;
    getPilgrims(id: string, tenantId: string): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }[]>;
    update(id: string, updateBookingDto: UpdateBookingDto, tenantId: string, currentUser: any): Promise<{
        package: {
            name: string;
            id: string;
            code: string;
        };
        customer: {
            name: string;
            id: string;
        };
    } & {
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    }>;
    remove(id: string, tenantId: string): Promise<void>;
    changeStatus(id: string, status: BookingStatus, tenantId: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    }>;
    cancel(id: string, reason?: string, tenantId?: string): Promise<{
        id: string;
        tenant_id: string;
        status: import(".prisma/client").$Enums.BookingStatus;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        room_type: import(".prisma/client").$Enums.RoomType;
        notes: string | null;
        customer_id: string;
        package_id: string;
        booking_code: string;
        payment_status: import(".prisma/client").$Enums.PaymentStatus;
        number_of_pilgrims: number;
        special_requests: string | null;
        base_price: number;
        tax_amount: number;
        additional_fees: number;
        discount_amount: number;
        total_price: number;
        dp_amount: number;
        dp_paid: number;
        remaining_amount: number;
        remaining_paid: number;
        total_paid: number;
        booking_date: Date;
        confirmation_date: Date | null;
        payment_complete_date: Date | null;
        departure_date: Date;
        return_date: Date;
        created_by: string;
        updated_by: string | null;
    }>;
    addPilgrims(id: string, pilgrimsData: any[], tenantId: string): Promise<{
        name: string;
        email: string | null;
        id: string;
        tenant_id: string;
        phone: string | null;
        status: string;
        created_at: Date;
        updated_at: Date;
        deleted_at: Date | null;
        address: string | null;
        id_type: string;
        id_number: string;
        birth_date: Date;
        gender: string;
        customer_id: string;
        booking_id: string;
        birth_place: string;
        passport_number: string | null;
        passport_expiry: Date | null;
        family_relationship: string;
        emergency_contact: import("@prisma/client/runtime/library").JsonValue | null;
        room_number: string | null;
        building: string | null;
        floor: number | null;
        documents: import("@prisma/client/runtime/library").JsonValue[];
        document_completion: number;
    }[]>;
    getStats(query: any, tenantId: string): Promise<{
        total: number;
        byStatus: {
            status: import(".prisma/client").$Enums.BookingStatus;
            count: number;
        }[];
        byPaymentStatus: {
            status: import(".prisma/client").$Enums.PaymentStatus;
            count: number;
        }[];
        recentCount: number;
        totalRevenue: number;
        topPackages: {
            package_id: string;
            count: number;
        }[];
    }>;
    exportToExcel(query: BookingQueryDto, tenantId: string): Promise<ExcelJS.Buffer>;
    sendNotifications(id: string, type: string, tenantId: string): Promise<void>;
    getCalendar(year: number, month: number, tenantId: string): Promise<{
        id: string;
        title: string;
        date: Date;
        status: import(".prisma/client").$Enums.BookingStatus;
        customerName: string;
        packageCode: string;
    }[]>;
    private generateBookingCode;
    private calculatePricing;
    private validateStatusTransition;
}
